feat: bump angular 17
ng-matero/extensions pull request #262
Opened 2023-11-10 07:02 UTC by damingerdai

related: #261

2023-11-10 07:25 UTC, damingerdai commented
<img width="794" alt="image" src="https://github.com/ng-matero/extensions/assets/16384908/b2c942ac-04cc-451b-b9b5-175e2e893171">

2023-11-10 07:43 UTC, damingerdai commented
> <img alt="image" width="794" src="https://user-images.githubusercontent.com/16384908/281988126-b2c942ac-04cc-451b-b9b5-175e2e893171.png">

fix it by [fix(multiple): ensure all public theming mixins are exposed at top-level](https://github.com/ng-matero/extensions/issues/261)

2023-11-16 15:32 UTC, LanderBeeuwsaert commented
@damingerdai we would want to upgrade to angular 17 already but are blocked by this.
Is it possible to somehow install your branch and use that?
I've tried with different variations of:
"@ng-matero/extensions": "github:@ng-matero/extensions.git#damingerdai:feat/261",
and even tried cloning your forked repository instead but I don't get it working. Possibly I'm doing something wrong?
Would be great if you can give me a pointer!

2023-11-17 03:51 UTC, damingerdai commented
@nzbin please review

2023-11-17 10:20 UTC, A77AY requested changes

2023-11-17 10:20 UTC, A77AY commented on package.json
>      "@ng-select/ng-select": "^11.1.0",
Need to update to 12

2023-11-19 08:58 UTC, merged